site_name: UserProfileService Documentation
repo_url: https://github.com/bechtleav360/Maverick.UserProfileService

docs_dir: docs

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

plugins: 
  - search
  - mermaid2
  - awesome-pages
  - macros
  - print-site

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets