// Implementation based on C# driver implementation from https://github.com/yojimbo87/ArangoDB-NET 
// with some bug fixes and extensions to support asynchronous operations 
namespace Maverick.Client.ArangoDb.Protocol;

internal static class ParameterName
{
    internal const string Action = "action";
    internal const string BatchSize = "batchSize";
    internal const string BindVars = "bindVars";
    internal const string Body = "body";
    internal const string Cache = "cache";
    internal const string Code = "code";
    internal const string Collection = "collection";
    internal const string Collections = "collections";
    internal const string Count = "count";
    internal const string Direction = "direction";
    internal const string DistributeShardsLike = "distributeShardsLike";
    internal const string DoCompact = "doCompact";
    internal const string ExcludeSystem = "excludeSystem";
    internal const string ExpireAfter = "expireAfter";
    internal const string Fields = "fields";
    internal const string From = "from";
    internal const string GeoJson = "geoJson";
    internal const string Group = "group";
    internal const string HeaderEndpoint = "X-Arango-Endpoint";
    internal const string HeaderforceDirtyRead = "X-Arango-Allow-Dirty-Read";
    internal const string IfMatch = "If-Match";
    internal const string IfNoneMatch = "If-None-Match";
    internal const string IgnoreRevs = "ignoreRevs";
    internal const string IndexBuckets = "indexBuckets";
    internal const string IsDeterministic = "isDeterministic";
    internal const string IsSystem = "isSystem";
    internal const string IsVolatile = "isVolatile";
    internal const string JournalSize = "journalSize";
    internal const string KeepNull = "keepNull";
    internal const string KeyOptionsAllowUserKeys = "keyOptions.allowUserKeys";
    internal const string KeyOptionsIncrement = "keyOptions.increment";
    internal const string KeyOptionsOffset = "keyOptions.offset";
    internal const string KeyOptionsType = "keyOptions.type";
    internal const string LockTimeout = "lockTimeout";
    internal const string MaxTransactionSize = "maxTransactionSize";
    internal const string MemoryLimit = "memoryLimit";
    internal const string MergeObjects = "mergeObjects";
    internal const string MinLength = "minLength";
    internal const string Name = "name";
    internal const string Namespace = "namespace";
    internal const string NumberOfShards = "numberOfShards";
    internal const string OptionsFullCount = "options.fullCount";
    internal const string OptionsMaxPlans = "options.maxPlans";
    internal const string OptionsOptimizerRules = "options.optimizer.rules";
    internal const string Overwrite = "overwrite";
    internal const string OverWriteMode = "overwriteMode";
    internal const string Params = "params";
    internal const string Query = "query";
    internal const string ReplicationFactor = "replicationFactor";
    internal const string ReturnNew = "returnNew";
    internal const string ReturnOld = "returnOld";
    internal const string ShardingStrategy = "shardingStrategy";
    internal const string ShardKeys = "shardKeys";
    internal const string Silent = "silent";
    internal const string SmartJoinAttribute = "smartJoinAttribute";
    internal const string Sparse = "sparse";
    internal const string To = "to";
    internal const string TransactionId = "x-arango-trx-id";
    internal const string Ttl = "ttl";
    internal const string Type = "type";
    internal const string Unique = "unique";
    internal const string Vertex = "vertex";
    internal const string WaitForSync = "waitForSync";
    internal const string WithData = "withData";
    internal const string WithRevisions = "withRevisions";
    internal const string WriteConcern = "writeConcern";
}
